language: go

go:
  - 1.7.4

branches:
  only:
    - master
    - criteo

script:
  - find . -type f -name "*go" | xargs sed 's|github.com/hashicorp/consul|github.com/criteo-forks/consul|' -i
  - make ci

sudo: false
